export const MES_TABS = [
  {
    key: "sales",
    label: "수주",
    views: [{ viewKey: "mes2-delivery-risk-detail", title: "납기 임박 미완료 수주" }],
  },
  {
    key: "production",
    label: "생산",
    views: [
      { viewKey: "mes2-card-production-result", title: "생산 실적" },
      { viewKey: "mes2-card-incomplete-work", title: "미완료 작업" },
      { viewKey: "mes2-forecast-work-depletion", title: "작업 소진 전망" },
      { viewKey: "mes2-production-trend-14d", title: "생산 실적 추이(14일)" },
    ],
  },
  {
    key: "delivery",
    label: "납기",
    views: [
      { viewKey: "mes2-card-delivery-risk", title: "납기 임박 미완료 수주 집계" },
      { viewKey: "mes2-forecast-delivery-delay", title: "향후 7일 납기 지연 예상" },
    ],
  },
  {
    key: "equipment",
    label: "설비",
    views: [
      { viewKey: "machine-operation-rate-weekly", title: "설비별 가동률(일주일)" },
    ],
  },
  {
    key: "quality",
    label: "품질",
    views: [
      { viewKey: "mes2-card-inspection", title: "검사 실시" },
      { viewKey: "mes2-quality-instrument-management", title: "품질·계측기 관리" },
    ],
  },
] as const;

export type MesTabKey = (typeof MES_TABS)[number]["key"];

export const DEFAULT_MES_TAB: MesTabKey = "sales";

export const MES_VIEW_COLUMN_LABELS: Record<string, Record<string, string>> = {
  "mes2-card-production-result": {
    REPORT_DATE: "기준일",
    RESULT_COUNT: "실적건수",
    WORK_ORDER_COUNT: "작업지시수",
    RESULT_QTY: "실적수량",
    ACTIVE_EQUIPMENT_COUNT: "가동설비수",
    WORKER_COUNT: "작업자수",
  },
  "mes2-card-incomplete-work": {
    REPORT_DATE: "기준일",
    INCOMPLETE_COUNT: "미완료건수",
    NOT_STARTED_COUNT: "미착수건수",
    IN_PROGRESS_COUNT: "진행중건수",
    TOP_PROCESS_SEQ: "최다공정순서",
    TOP_PROCESS_NAME: "최다공정명",
    TOP_PROCESS_COUNT: "최다공정건수",
  },
  "mes2-card-delivery-risk": {
    REPORT_DATE: "기준일",
    URGENT_COUNT: "긴급대상건수",
    OVERDUE_COUNT: "납기경과(최대30일)건수",
    DUE_WITHIN_7_COUNT: "7일이내건수",
    DUE_WITHIN_8_TO_30_COUNT: "8~30일이내건수",
    TOTAL_RISK_COUNT: "전체위험건수",
  },
  "mes2-delivery-risk-detail": {
    REPORT_DATE: "기준일",
    ORDER_ID: "수주번호",
    ORDER_SEQ: "수주일련번호",
    ITEM_CD: "품목코드",
    ITEM_NM: "품목명",
    CUST_CD: "거래처코드",
    CUST_NM: "거래처명",
    DELIVERY_DATE: "납기일",
    REMAINING_DAYS: "잔여일",
    ORDER_QTY: "수주수량",
    TOTAL_PROCESS_COUNT: "전체공정수",
    COMPLETED_PROCESS_COUNT: "완료공정수",
    FIRST_INCOMPLETE_PROCESS: "최초미완공정",
    FIRST_INCOMPLETE_PROCESS_NM: "최초미완공정명",
  },
  "mes2-card-inspection": {
    REPORT_DATE: "기준일",
    PERIOD_START_DATE: "집계시작일",
    PERIOD_END_DATE: "집계종료일",
    INSPECTION_COUNT: "전체검사건수",
    RECEIVING_INSPECTION_COUNT: "입고검사건수",
    FIRST_ARTICLE_INSPECTION_COUNT: "초품검사건수",
    PROCESS_INSPECTION_COUNT: "공정검사건수",
    FINAL_INSPECTION_COUNT: "최종검사건수",
    ACCEPT_QTY: "합격수량",
    DEFECT_QTY: "불량수량",
    COMPLETED_WORK_ORDER_COUNT: "완료작업지시수",
    FINAL_INSPECTED_WORK_ORDER_COUNT: "최종검사실시작업지시수",
    FINAL_INSPECTION_RATE: "최종검사실시율",
  },
  "mes2-quality-instrument-management": {
    REPORT_DATE: "기준일",
    INSPECTION_START_DATE: "검사집계시작일",
    INSPECTION_END_DATE: "검사집계종료일",
    RECEIVING_INSPECTION_COUNT: "입고검사건수",
    PROCESS_FINAL_INSPECTION_COUNT: "공정·최종검사건수",
    INSPECTION_COUNT_7D: "최근7일검사건수",
    CALIBRATION_EQUIPMENT_COUNT: "교정관리계측기수",
    EXPIRED_CALIBRATION_COUNT: "교정만료계측기수",
    DUE_WITHIN_30_DAYS_COUNT: "30일내교정계측기수",
    LATEST_DEFECT_DATE: "최근불량발생일",
    LATEST_DEFECT_REASON_CODE: "최근불량원인코드",
    LATEST_DEFECT_REASON_NAME: "최근불량원인",
    LATEST_DEFECT_QTY: "최근불량수량",
  },
  "mes2-forecast-delivery-delay": {
    REPORT_DATE: "기준일",
    FORECAST_START_DATE: "전망시작일",
    FORECAST_END_DATE: "전망종료일",
    TARGET_ORDER_COUNT: "7일내납기대상수",
    FORECASTABLE_ORDER_COUNT: "전망가능수주수",
    UNFORECASTABLE_ORDER_COUNT: "전망불가수주수",
    P20_DELAY_COUNT: "P20지연예상수",
    P50_DELAY_COUNT: "P50지연예상수",
    P80_DELAY_COUNT: "P80지연예상수",
  },
  "mes2-forecast-work-depletion": {
    REPORT_DATE: "기준일",
    PERIOD_START_DATE: "집계시작일",
    PERIOD_END_DATE: "집계종료일",
    INCOMPLETE_COUNT: "미완료작업수",
    COMPLETED_COUNT_28D: "최근28일완료수",
    DAILY_AVERAGE_COMPLETED_COUNT: "일평균완료수",
    NEW_WORK_COUNT_28D: "최근28일신규지시수",
    DAILY_AVERAGE_NEW_WORK_COUNT: "일평균신규지시수",
    DAILY_NET_REDUCTION_COUNT: "일평균순감소수",
    GROSS_DEPLETION_DAYS: "단순소진일수",
    NET_DEPLETION_DAYS: "순소진일수",
    DEPLETION_STATUS: "소진상태",
  },
  "mes2-production-trend-14d": {
    REPORT_DATE: "기준일",
    PERIOD_START_DATE: "집계시작일",
    PERIOD_END_DATE: "집계종료일",
    RESULT_DATE: "실적일",
    RESULT_COUNT: "실적건수",
    WORK_ORDER_COUNT: "작업지시수",
    ACTIVE_EQUIPMENT_COUNT: "가동설비수",
    AVERAGE_RESULT_COUNT: "일평균실적건수",
    MAX_RESULT_COUNT: "최대실적건수",
    MIN_RESULT_COUNT: "최소실적건수",
  },
  "machine-operation-rate-weekly": {
    BASE_DATE: "기준일",
    MACHINE_CODE: "설비코드",
    MACHINE_NAME: "설비명",
    MACHINE_EXPRESS: "설비표시순서",
    OPERATION_SECONDS: "가동시간(초)",
    OPERATION_RATE: "가동률",
  },
};
